### ISSUE TITLE
validate input data against user-provided schema

### ISSUE THREAD

**Issue by ascourtas** [DLHub-Argonne/dlhub_sdk#133]
Currently, we require servable publishers to specify the type and format of the servable's expected input, but we don't validate it -- thus, if a user inputs the wrong input shape/type at runtime, they are left with whatever error the publisher's code would produce, which is highly variable and could be uninformative.

It would be helpful to validate the input the user supplies to the servable. This could perhaps be validated in `dl.run()` before the call to `funcx_client.run()`, where we create a function to fetch the named servable's expected input format and compared that to the provided input.

Input validation should consist of a conditional check where we compare the provided inputs with the inputs described in the model metadata.

**Comment by isaac-darling** [comment]
I poked around the `DLHubClient` definition and its dependencies, but I didn't find where the "model metadata" is stored. Where should that be pulled from?

**Comment by ascourtas** [comment]
Hi @isaac-darling , great question. When the servable is published to DLHub, the metadata are written to a `dlhub.json` file (seen [here](https://github.com/DLHub-Argonne/dlhub_sdk/blob/master/dlhub_sdk/client.py#L361)). That file is accessible in the Search record (where "Search" here is Globus Search, our database management service). 

My first suggestion would be trying to access that record using this method or a similar one. If that does not return what you need (i.e. the `dlhub.json` content in whatever blob is returned), then I would suggest making a new "private" function to fetch the metadata based on servable name, ID, etc.

**Comment by ascourtas** [comment]
in honor of the effort and scale of this task, I am bumping it up to advanced 🔥

**Comment by WardLT** [comment]
And @isaac-darling is def doing 'advanced' work
