### ISSUE TITLE
add capability to run model using only model DOI

### ISSUE THREAD

**Issue by ascourtas** [DLHub-Argonne/dlhub_sdk#148]
Can look at the Foundry dataset DOI logic to accomplish something similar for DLHub models

`is_doi()`: https://github.com/MLMI2-CSSI/foundry/blob/2f124544d5f05e9ee401fe2aaa3ed2208051578f/foundry/foundry.py#L803

use of `is_doi()`:
https://github.com/MLMI2-CSSI/foundry/blob/2f124544d5f05e9ee401fe2aaa3ed2208051578f/foundry/foundry.py#L159

**Comment by WardLT** [comment]
I'd say this is different, as the DOI maps to the most-recent version of a model (all versions of the model should share a DOI) and the unique identifier in #99 should point to a specific version (at least that's my opinion 🙃 )

**Comment by ascourtas** [comment]
great! So this issue will be for running a model based on DOI, and #99 will be for running a model based on UUID

**Comment by blaiszik** [comment]
Most models do not have DOIs, we may need to add some of these into the DLHub metadata.

It should be in datacite (or dc).identifiers field

**Comment by BenGalewsky** [comment]
Will become a garden story
