### ISSUE TITLE
No publication date on 1d_norm models.

### ISSUE THREAD

**Issue by MaxTuecke** [DLHub-Argonne/dlhub_sdk#49]
When running client.search on any of the 1d_norm models, I get a "RuntimeWarning: Found entries in DLHub index that lack publication_date. Please contact DLHub team" warning.

**Comment by WardLT** [comment]
I think this is from a servable that was published before we started putting publication dates on our models.

@ryanchard Do we have a planned date for wiping the Search index?

**Comment by ryanchard** [comment]
This seems like a good thing to do. We previously talked about changing some of the types again to help with range searching etc. Perhaps we should make a quick list of the things we want the new index to have so we don't end up doing this many times.

**Comment by WardLT** [comment]
Agreed. I'll take a look at the schemas tomorrow and mark what should go in Search and in what form. 

Hopefully, we're getting close to stable on the schemas.

**Comment by blaiszik** [comment]
@WardLT @ryanchard Have we wiped the index and reindexed with everything in the latest schema?
