### ISSUE TITLE
Unit Tests are Filling Search Index with Junk

### ISSUE THREAD

**Issue by WardLT** [DLHub-Argonne/dlhub_sdk#68]
Even with the "publish model" test only running on Travis, it is adding a lot of noise to the DLHub Search Index. 

There are a couple of ways to address this:

- Add a "test" flag to the DLHub schema and have the website screen them out
- Limit the visibility of the test-related models
- Delete the models after the test

(reported by @blaiszik )

**Comment by blaiszik** [comment]
I think this has been fixed with the added test flag
