### ISSUE TITLE
Keras models are missing tensorflow dependency

### ISSUE THREAD

**Issue by blaiszik** [DLHub-Argonne/dlhub_sdk#71]
Not sure why this is just coming up now, but Keras models are failing to build without tensorflow as a dependency. Manually adding tensorflow seems to solve the problem, so we should add it as an automatic dependency unless I am missing something...

**Comment by WardLT** [comment]
Interesting. In retrospect, we should determine the backend and list it (TF or otherwise) as a dependency. 

@ryanchard: Was tensorflow automatically part of any our containers? If so, has that changed?
