### ISSUE TITLE
Update `get_task_status()` to meet funcX schema 

### ISSUE THREAD

**Issue by WardLT** [DLHub-Argonne/dlhub_sdk#78]
Our status messages for tasks have changed, which causes some issues for my scripts.

We should document the expected format for the returns of "get_task_status."

@ryanchard , should I also file this issue with FuncX?

EDIT 6/14/22: The goal here is to update the method `get_task_status()` in the DLHub SDK to match whatever schema is expected from the [funcX SDK's `get_task()`](https://funcx.readthedocs.io/en/stable/reference/client.html?highlight=get%20task%20status#funcx.FuncXClient.get_task)

**Comment by WardLT** [comment]
That would be my guess. 2020 is ancient in FuncX API world.

**Comment by ascourtas** [comment]
may be deprecated, unclear if still useful with container service and current versions of funcx
